#!/usr/bin/python
#
# Copyright (C) 2011 Ivo Nunes
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
import sys
import os

repository = sys.argv[1]

os.system("cd /etc; sed -i 's/DISTRIB_ID=GenOS/DISTRIB_ID=Ubuntu/g' lsb-release; sed -i 's/DISTRIB_CODENAME=GenOS/DISTRIB_CODENAME=maverick/g' lsb-release")
os.system("add-apt-repository " + repository)
os.system("cd /etc; sed -i 's/DISTRIB_ID=Ubuntu/DISTRIB_ID=GenOS/g' lsb-release; sed -i 's/DISTRIB_CODENAME=maverick/DISTRIB_CODENAME=GenOS/g' lsb-release")